# Conflux eSpace RPC Configurations
eth:
  ws: ws://evmtestnet.confluxrpc.com/ws
  http: http://evmtestnet.confluxrpc.com
  # retry: 3
  # retryInterval: 1s
  # requestTimeout: 3s

# Store Configurations
store:
  sqlite:
    # Use in-memory sqlite as default.
    # You can also specify path to a file (eg., `gorm.db`) for disk persistence.
    # database: file::memory:?cache=shared

# Metrics Configurations
metrics:
  enabled: false
  namespace: f2n
  influxdb:
    host: http://127.0.0.1:8086
    db:   web3pay
    username:
    password:
  report:
    enabled: false
    interval: 10s

# Logs Configurations
log:
  level: debug

# Alert Configurations
alert:
  customTags: [web3pay, test]
  dingtalk:
    enabled: false
    webhook: https://oapi.dingtalk.com/robot/send?access_token=${test_access_token}
    secret: ${test_secret}
    atMobiles: []
    isAtAll: false
